--- 
extensions: 
- json
- another-extension
name: bzz-rhodes
bbver: 4.6
sdk: /var/lib/gems/1.8/gems/rhodes-2.2.3
applog: rholog.txt
build: debug
wmsdk: Windows Mobile 6 Professional SDK (ARMV4I)
version: 1.0
vendor: rhomobile
sdkversion: 2.2.3
iphone: 
  provisionprofile: 
  sdk: iphonesimulator4.0
  entitlements: 
  codesignidentity: 
  configuration: Debug
