--- 
name: bzz-rhodes
extensions: 
- json
- another-extension
bbver: 4.6
sdk: /var/lib/gems/1.8/gems/rhodes-2.2.6
android: 
  version: 2.1
build: debug
applog: rholog.txt
version: 1.0
wmsdk: Windows Mobile 6 Professional SDK (ARMV4I)
sdkversion: 2.2.5
vendor: rhomobile
iphone: 
  provisionprofile: 
  sdk: iphonesimulator4.0
  codesignidentity: 
  entitlements: 
  configuration: Debug
